before_install:
  - gem update bundler
gemfile:
  - gemfiles/Gemfile.rails-4.0
  - gemfiles/Gemfile.rails-4.1
  - gemfiles/Gemfile.rails-4.2
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.3
  - jruby-19mode
  - rbx-2
matrix:
  allow_failures:
    - rvm: rbx-2
    - gemfile: gemfiles/Gemfile.rails-4.1
      rvm: jruby-19mode
